version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo npm install -g esy@next

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "esy.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: esy install

      - save_cache:
          paths:
            - node_modules
            - ~/.esy
          key: v2-dependencies-{{ checksum "esy.json" }}

      # run tests!
      - run: esy b

      - store_artifacts:
          path: ./_build/default/src/Bin.exe

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/repo
    steps:
      - run:
          name: "Publish Release on GitHub"
          command: |
            FILE=./_build/default/src/Bin.exe
            VERSION=$(my-binary --version)
            curl -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: $(file -b --mime-type $FILE)" --data-binary @$FILE "https://uploads.github.com/repos/jaredly/reason-language-server/releases/${CIRCLE_TAG}/assets?name=bin.linux.exe"

workflows:
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/